# Generated by Django 5.2.3 on 2025-06-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Основное содержание')),
                ('location', models.CharField(max_length=150, verbose_name='Место')),
                ('category', models.CharField(choices=[('travel_tips', 'Советы путешественникам'), ('historical_facts', 'Исторические факты'), ('magical_places', 'Магические места')], default='travel_tips', max_length=20, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Пост гида',
                'verbose_name_plural': 'Посты гида',
                'ordering': ['-created_at'],
            },
        ),
    ]
